language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t hars1014/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hars1014/client-test npm run test

after_success:
    - docker build -t hars1014/sample-worker -f ./worker/Dockerfile.prod ./worker
    - docker build -t hars1014/sample-client -f ./client/Dockerfile.prod ./client
    - docker build -t hars1014/sample-nginx -f ./nginx/Dockerfile.prod ./nginx
    - docker build -t hars1014/sample-api -f ./api/Dockerfile.prod ./api
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
    # Task to push the image to docker hub for fetching it by elastic bean stalk
    - docker push hars1014/sample-worker
    - docker push hars1014/sample-client
    - docker push hars1014/sample-nginx
    - docker push hars1014/sample-api
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-container-docker"
    env: "MultiContainerDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-712991057399"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY